<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lucky" failures="1" tests="2" name="Errorvalidation Test" time="28.815" errors="0" timestamp="2024-08-06T15:33:00 IST">
  <testcase classname="Pranavraj.AppiumFrameWorkDesign.ErrorChecking" name="FilForm_exceptional" time="11.584">
    <failure type="java.lang.AssertionError" message="expected [Please your name] but found [Please enter your name]">
      <![CDATA[java.lang.AssertionError: expected [Please your name] but found [Please enter your name]
at Pranavraj.AppiumFrameWorkDesign.ErrorChecking.FilForm_exceptional(ErrorChecking.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- FilForm_exceptional -->
  <testcase classname="Pranavraj.AppiumFrameWorkDesign.ErrorChecking" name="FilForm_positive" time="4.073"/>
</testsuite> <!-- Errorvalidation Test -->
